---
- name: Deploy Nginx Web Server
  hosts: webservers
  become: true

  tasks:
    - name: user deploy
      ansible.builtin.user:
        name: deploy
        shell: /bin/bash
        state: present

    - name: create main file web
      ansible.builtin.file:
        path: /var/www/myapp
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: DÃ©marrer Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: create main file web
      ansible.builtin.file:
        path: /var/www/myapp
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'
        
    - name: deploy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/myapp/index.html
        owner: deploy
        group: deploy
        mode: '0644'